name: Package-CLI-Artifacts
on:
  push:
    branches:
      - main
      - develop
      - feature/* 

permissions:
    id-token: write
    contents: read

concurrency:
  group: ${{ github.workflow }} - ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  Package-Cli:
    name: Package-Cli
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: create-tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          tag_prefix: v

      - name: Create a GitHub release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.create-tag.outputs.new_tag }}
          name: Release ${{ steps.create-tag.outputs.new_tag }}
          body: ${{ steps.create-tag.outputs.changelog }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      
      - name: Set launchSetting.json ENV variable
        working-directory: ./.github 
        run:  echo "LAUNCH_SETTINGS_FILE=$(cat ./launchSettings.json | sed s/{{CLI_OPENAI_KEY}}/${{ secrets.OPENAI_API_KEY }}/)" >> $GITHUB_ENV

      - name: Build Post Commit Launch Settings
        working-directory: ./CLI/GitHooks/PostCommitMsgApp/Properties
        run: echo '${{ env.LAUNCH_SETTINGS_FILE }}' >> launchSettings.json

      - name: Build Post Commit Launch Settings
        working-directory: ./CLI/OpenaiSummarizer/Properties
        run: echo '${{ env.LAUNCH_SETTINGS_FILE }}' >> launchSettings.json

      - name: Build and Upload CliApp
        uses: ./.github/actions/build-and-publish-artifact
        with:
          os: ${{ matrix.os }}
          project-directory: ./CLI/CliApp
          artifact-name: CliApp.exe
          upload-url: ${{ steps.create-release.outputs.upload_url }}
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build and Upload Commit Message Hook
        uses: ./.github/actions/build-and-publish-artifact
        with:
          os: win
          project-directory: ./CLI/GitHooks/CommitMsgApp
          artifact-name: CommitMsgApp.exe
          artifact-new-name: commit-msg.exe
          upload-url: ${{ steps.create-release.outputs.upload_url }}
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build and Upload Commit Message Hook
        uses: ./.github/actions/build-and-publish-artifact
        with:
          os: win
          project-directory: ./CLI/GitHooks/PostCommitMsgApp
          artifact-name: PostCommitMsgApp.exe
          artifact-new-name: post-commit.exe
          upload-url: ${{ steps.create-release.outputs.upload_url }}
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}

