name: Package-CLI-Artifacts
on:
  push:
    branches:
      - main
      - develop
      - feature/cli_ci_cd

permissions:
    id-token: write
    contents: read

concurrency:
  group: ${{ github.workflow }} - ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  Package-Cli:
    name: Package-Cli
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: win
            ext: .exe
          - os: linux
            ext: ""
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Create Release Tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          tag_prefix: v

      - name: Create Release
        id: create-release
        uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}

      - name: Build and Upload CliApp
        uses: ./actions/build-and-publish-artifact
        with:
          os: ${{ matrix.os }}
          project-directory: ./CLI/CliApp
          artifact-name: CliApp${{ matrix.ext }}
          upload_url: ${{ steps.create-release.outputs.upload_url }}

      - name: Builda and Upload Commit Message Hook
        uses: ./actions/build-and-publish-artifact
        with:
          os: ${{ matrix.os }}
          project-directory: ./CLI/GitHook/CommitMsgApp
          artifact-name: CommitMsgApp${{ matrix.ext }}
          artifact-new-name: commit-msg${{ matrix.ext }}
          upload_url: ${{ steps.create-release.outputs.upload_url }}

      - name: Builda and Upload Commit Message Hook
        uses: ./actions/build-and-publish-artifact
        with:
          os: ${{ matrix.os }}
          project-directory: ./CLI/GitHook/PostCommitMsgApp
          artifact-name: PostCommitMsgApp${{ matrix.ext }}
          artifact-new-name: post-commit${{ matrix.ext }}
          upload_url: ${{ steps.create-release.outputs.upload_url }}
